Query resubmission in JDBC client
hazelcast/hazelcast-jdbc pull request #185
Opened 2022-07-20 09:16 UTC by krzysztofslusarski

TDD: https://github.com/hazelcast/hazelcast/pull/21369

2022-07-25 16:56 UTC, viliam-durina requested changes

2022-07-25 16:56 UTC, viliam-durina commented on src/main/java/com/hazelcast/jdbc/HazelcastConfigFactory.java
> +            String message = String.format("'%s' not valid for SQL resubmission mode, '%s'", key, value);
key/value is swapped in the msg:
```suggestion
            String message = String.format("'%s' not a valid value for '%s'", value, key);
```

We should also cover it in a test where it would be more obvious.

2022-08-08 19:49 UTC, krzysztofslusarski commented on src/main/java/com/hazelcast/jdbc/HazelcastConfigFactory.java
> +            String message = String.format("'%s' not valid for SQL resubmission mode, '%s'", key, value);
Done

2022-08-23 16:07 UTC, viliam-durina approved these changes

2022-08-25 10:10 UTC, Fly-Style approved these changes

2022-08-25 10:13 UTC, merged