Basic implementation for simple queries
hazelcast/hazelcast-jdbc pull request #2
Opened 2020-11-30 15:20 UTC by SeriyBg

Basic implementation for simple queries without the support of different env and data types

2020-11-30 15:20 UTC, devOpsHazelcast commented
[![CLA assistant check](https://cla.hazelcast.org/pull/badge/not_signed)](https://cla.hazelcast.org/hazelcast/hazelcast-jdbc?pullRequest=2) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.hazelcast.org/hazelcast/hazelcast-jdbc?pullRequest=2) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.hazelcast.org/check/hazelcast/hazelcast-jdbc?pullRequest=2) it.</sub>

2020-12-02 13:57 UTC, pivovarit requested changes
Additionally, I think we should be throwing SQLFeatureNotSupportedException instead of failing silently.

Let's say I want to execute an update and in return, I will get information that zero rows were changed which suggests that the update was actually executed why it was not even attempted.

2020-12-02 13:57 UTC, pivovarit commented on src/main/java/com/hazelcast/jdbc/Driver.java
> +            exception.printStackTrace();
That requires better handling

2020-12-02 13:57 UTC, pivovarit commented on src/main/java/com/hazelcast/jdbc/HazelcastJdbcPreparedStatement.java
> +        parameters = new ArrayList<>();
Why not initialize at the field level?

2020-12-02 13:57 UTC, pivovarit commented on src/main/java/com/hazelcast/jdbc/HazelcastJdbcStatement.java
> +    private static final int MILLIS_IN_SECOND = 1_000;
Would be easier to do conversions if you relied on `java.time`'s `Duration` (assuming we don't need to support JDKs older than 1.8 )

2020-12-02 14:15 UTC, SeriyBg commented on src/main/java/com/hazelcast/jdbc/Driver.java
> +        HazelcastInstance client = HazelcastClient.newHazelcastClient(clientConfig);
This is true. The plan is to add the pooling in the future PR, probably together with the config parameters

2020-12-02 16:22 UTC, SeriyBg commented on src/main/java/com/hazelcast/jdbc/Driver.java
> +        return url != null && url.toLowerCase().startsWith(URL_PREFIX);
Not sure that I understand your point here. As far I can see we don't need the `URL`object and the validation will have to be implemented anyway as it does not support `jdbc` protocol by default

2020-12-02 16:23 UTC, SeriyBg commented on src/test/java/com/hazelcast/jdbc/HazelcastJdbcDriverTest.java
> +        member.getConfig().addMapConfig(config);
Indeed :) Removed it

2020-12-02 16:41 UTC, pivovarit commented on src/main/java/com/hazelcast/jdbc/Driver.java
> +        return url != null && url.toLowerCase().startsWith(URL_PREFIX);
Sorry, meant `URI` and not `URL`. It should simplify parsing since you can just create an object and then access individual parts of the URI using `getScheme()/getSchemeSpecificPart()`

`URI uri = URI.create("jdbc:hazelcast://localhost:5701");`

2020-12-02 17:32 UTC, SeriyBg commented on src/main/java/com/hazelcast/jdbc/Driver.java
> +        return url != null && url.toLowerCase().startsWith(URL_PREFIX);
Oh, I see. Yes, that makes sense, but we will have to create it from the substring after `jdbc:`, as `jdbc:hazelcast://` is not parsed as a valid schema according to URI standards

`URI uri = URI.create("hazelcast://localhost:5701");`

2020-12-02 17:36 UTC, pivovarit commented on src/main/java/com/hazelcast/jdbc/Driver.java
> +        return url != null && url.toLowerCase().startsWith(URL_PREFIX);
To be honest, I thought that RFC-3986 covered something like `jdbc:hazelcast`. Well, hope it's helpful regardless

2020-12-02 17:52 UTC, SeriyBg commented on src/main/java/com/hazelcast/jdbc/Driver.java
> +        return url != null && url.toLowerCase().startsWith(URL_PREFIX);
It will be. For connections itself, it will be useful for sure

2020-12-07 07:31 UTC, devozerov commented on .gitignore
> +.idea/caches/build_file_checksums.ser
This file looks like a copy-paste from somewhere. We do not use Android studio, Gradle, Mongo Explorer, etc. 
`.gitignore` from IMDG or Jet repos should be sufficient (with small modifications to remove unnecessary stuff).

2020-12-07 07:32 UTC, devozerov commented on pom.xml
> +      <version>${hazelcast.version}</version>
The SQL module should not be required for JDBC, since this is a server-side dependency.

2020-12-07 07:33 UTC, devozerov commented on pom.xml
> +    <hazelcast.version>4.1</hazelcast.version>
Shouldn't we use the `SNAPSHOT` version here, similarly to Jet?

2020-12-07 07:35 UTC, devozerov commented on pom.xml
> +        <version>5.7.0</version>
We use 4.x JUnit version in IMDG and Jet. Is it ok to use a different dependency here? This will complicate things significantly, as developers of differents parts of the product would have to learn different APIs, and it will be difficult to open both projects in IDE at the same time. 
Do we have any governing rules on dependency version selection across different parts of the product?

2020-12-07 07:37 UTC, pivovarit commented on pom.xml
> +    <hazelcast.version>4.1</hazelcast.version>
It depends on which is the minimum supported version. Additionally, we could build it against a snapshot, but shouldn't we rely on the last stable version?

2020-12-07 07:38 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/Driver.java
> +    private static final int VER_MAJOR = 1;
We need to decide which version to use for the first release. Should it start from 1.x, or from 4.x?

2020-12-07 07:39 UTC, pivovarit commented on pom.xml
> +        <version>5.7.0</version>
APIs are almost the same and JUnit 5 is backward compatible. Integrations juggle with many more dependencies across multiple projects daily. I see no issue here

2020-12-07 07:40 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/Driver.java
> +        if (!url.toLowerCase().startsWith(URL_PREFIX)) {
Is JDBC URL case sensitive or not according to the standard? I.e. should `jdbc:hazelcast` and `JDBC:hazelcast` be treated as the same prefix?

2020-12-07 07:48 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/Driver.java
> +        URI uri = pareUrl(url);
I would discourage the usage of URL parsing logic unless we are 100% sure that our URL will be compliant. JDBC URLs could take any form, with paths, special characters, etc. For example, take a look at SQL Server URL used for IPv6 connection, which is not compliant: https://docs.microsoft.com/en-us/sql/connect/jdbc/building-the-connection-url?view=sql-server-ver15#connecting-with-ipv6-addresses
Typically, the connection string is parsed manually by vendors, to handle all the intricacies of the provided capabilities properly.

2020-12-07 08:00 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/Driver.java
> +    public Connection connect(String url, Properties info) throws SQLException {
Looks like the schema is not supported here. Schema management is a foundational part of the driver, so it should be handled right away.

2020-12-07 08:05 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/JdbcConnection.java
> +    public <T> T unwrap(Class<T> iface) throws SQLException {
`unwrap` and `isWrapperFor` methods do not require a "closed" check as per docs.

2020-12-07 08:10 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/JdbcConnection.java
> +        checkClosed();
Not all required checks are performed here (`executor` is null, `milliseconds` is less than zero). 

Also, we lose the passed value here, and the subsequent call to `getNetworkTimeout` will return zero regardless. Even though we do not support the network timeout at the moment, it may make sense to pass the value through.

2020-12-07 08:10 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/JdbcConnection.java
> +        checkClosed();
Shouldn't this method call `close` (as per JavaDocs)?

2020-12-07 08:11 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/JdbcConnection.java
> +        checkClosed();
Scheme support is required even for the base version.

2020-12-07 08:12 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/JdbcConnection.java
> +    public Array createArrayOf(String typeName, Object[] elements) throws SQLException {
Since we do not support `createArrayOf` and `createStruct`, it is better to throw the "unsupported" exception, rather than exposing the user to possible NPE .

2020-12-07 08:16 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/JdbcConnection.java
> +    public void setClientInfo(String name, String value) throws SQLClientInfoException {
Check for a closed connection is required in `setClientInfo` methods as per JavaDoc.

2020-12-07 08:17 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/JdbcConnection.java
> +        return null;
Same as for `createStruct` methods - we'd better throw an exception here.

2020-12-07 08:21 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/JdbcConnection.java
> +        return null;
We cannot return `null` from here, because this method could be used by other products. Instead, the common approach is to delegate all `preparedStatement` overrides to this method, then check if the provided `resultSetType`, `resultSetConcurrency` and `resultSetHoldability` are supported (we should support at least one value for each), and then create the prepared statements object.

Similarly to `createStatement`.

2020-12-07 08:21 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/JdbcConnection.java
> +        return null;
Savepoint features are not supported. Should we throw an unsupported exception from this family of methods?

2020-12-07 08:24 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/JdbcConnection.java
> +        checkClosed();
This method has some shared concerns with the `auto-commit` flag (as per JavaDoc). Since we return `false` for `auto-commit`, the `rollback` method should fail always.

2020-12-07 08:26 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/JdbcConnection.java
> +        return 0;
We cannot return zero here. One of the constants (as per JavaDoc) should be returned.

2020-12-07 08:26 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/JdbcConnection.java
> +        return null;
Possible NPE. Perhaps it is better to throw an unsupported exception from `getTypeMap`, `setTypeMap`.

2020-12-07 08:27 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/JdbcConnection.java
> +        checkClosed();
As per JavaDoc, the passed value should be validated.

2020-12-07 08:27 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/JdbcConnection.java
> +        checkClosed();
As per JavaDoc, the passed value should be validated.

2020-12-07 08:29 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/JdbcConnection.java
> +        return null;
Until the metadata is implemented, it is better to throw an exception here instead of returning `null`, to have predictable behavior.

2020-12-07 08:29 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/JdbcConnection.java
> +        checkClosed();
The `auto-commit` flag should be checked here.

2020-12-07 08:41 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/HazelcastJdbcStatement.java
> +        return null;
`unwrap`/`isWrapperFor` should be implemented.

2020-12-07 08:42 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/HazelcastJdbcStatement.java
> +    public void closeOnCompletion() throws SQLException {
`closeOnCompletion` mechanics should be implemented as per JavaDocs.

2020-12-07 08:43 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/HazelcastJdbcStatement.java
> +        return poolable;
Closed check is required.

2020-12-07 08:43 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/HazelcastJdbcStatement.java
> +        return 0;
Zero is an invalid constant for this method.

2020-12-07 08:46 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/HazelcastJdbcStatement.java
> +        return false;
The family of "execute" methods should be implemented. If the unsupported argument is passed (e.g. `autoGeneratedKeys=true`, or `columnNames/columnIndexes` with non-zero length) we should throw an exception. Otherwise, the statement should be executed.

2020-12-07 08:47 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/HazelcastJdbcStatement.java
> +        return null;
It is better to throw an unsupported exception here, rather than return `null`.

2020-12-07 08:48 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/HazelcastJdbcStatement.java
> +        return false;
The `getMoreResults` method requires proper implementation, that will close the children result set as per that passed argument.

2020-12-07 08:49 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/HazelcastJdbcStatement.java
> +        return null;
Should return the parent connection

2020-12-07 08:50 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/HazelcastJdbcStatement.java
> +        return new int[0];
Since we do not support the execution of batches for now (are we?), we should throw an exception here.

2020-12-07 08:50 UTC, SeriyBg commented on .gitignore
> +.idea/caches/build_file_checksums.ser
It's created using the IDE plugin. Will clean it up and leave only the needed ignores

2020-12-07 08:50 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/HazelcastJdbcStatement.java
> +        return 0;
`getResultSetConcurrency` and `getResultSetType` should return valid constants instead of zero.

2020-12-07 08:51 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/HazelcastJdbcStatement.java
> +
`get/setFetchDirection` methods should be implemented properly: closed check, constant value validation, return proper constant.

2020-12-07 08:52 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/HazelcastJdbcStatement.java
> +        return false;
This method should delegate to `getMoreResults(CLOSE_CURRENT_RESULT)`.

2020-12-07 08:52 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/HazelcastJdbcStatement.java
> +        return 0;
Why zero? The executed statement could have returned the update count.

2020-12-07 08:53 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/HazelcastJdbcStatement.java
> +        return resultSet;
The method should strictly follows the semantics declared in JavaDoc.

2020-12-07 08:55 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/HazelcastJdbcStatement.java
> +        return false;
The `execute` method is one of the main entry points, next to `executeQuery` and `executeUpdate`. They all should be implemented even in the first version.

2020-12-07 08:56 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/HazelcastJdbcStatement.java
> +    public void setCursorName(String name) throws SQLException {
As we do not support cursor names, shouldn't we throw an unsupported exception from the `setCursorName`?

2020-12-07 08:57 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/HazelcastJdbcStatement.java
> +    public void cancel() throws SQLException {
Cancel is a very important method but is complicated to implement. Should we throw an unsupported exception for now, instead of ignoring the call?

2020-12-07 08:58 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/HazelcastJdbcStatement.java
> +        this.queryTimeout = Duration.ofSeconds(seconds);
The `setQueryTimeout` method should check for valid values as per JavaDoc.

2020-12-07 08:59 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/HazelcastJdbcStatement.java
> +        return 0;
`get/setMaxRows` methods are worth a separate issue.

2020-12-07 09:41 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/HazelcastJdbcPreparedStatement.java
> +
We should throw an unsupported operation exception from getters/setters that we do not support.

2020-12-07 09:46 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/HazelcastJdbcPreparedStatement.java
> +
Date/time/timestamp types are supported at the engine's level. We need to support them in JDBC as well, but maybe it is better to implement it in a separate issue.

2020-12-07 09:48 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/HazelcastJdbcResultSet.java
> +        T result = currentCursorPosition.getObject(columnLabel);
If I recall correctly, getters should do an implicit conversion when possible. For example, if we have a column of type `int`, and then we call `getLong`, then currently we will get a `ClassCastException`, while normally drivers will perform an implicit conversion. We need to consult to the specification, to understand what is the proper behavior depending on the type.

2020-12-07 09:56 UTC, devozerov commented
I conducted the review. General comments are:
1. We should be very careful with the semantics of every method of connection/statement/result set: follow the JavaDoc rules, prefer the unsupported exception over `null`, do no have methods without implementations (unless absolutely required), expose proper constant values, etc.
1. We need the implementations of the `execute` method family for both `Statement` and `PreparedStatement`: `execute`, `executeQuery`, `executeUpdate`. One problem here is that according to JDBC specification, a call to `executeQuery` should fail if the result is not an update count (and vice verse - `executeUpdate` fails if the result is a result set). The problem is that currently, we cannot enforce this failure unless the query is actually executed. To fix it, perhaps we would have to pass the "expectedResultType" flag to the SQL engine, which in turn would require a change to the protocol
1. Schema management is missing at the driver level for now. What is worse, it is not exposed to the SQL API. That is, we cannot pass the schema to the `SqlStatement` for now. This should be relatively straightforward to fix but would require additional testing and changes to the client protocol. Perhaps we should implement it separately in the JDBC driver, once the SQL engine API is updated accordingly
1. We need to add the proper management of states of the Statement and ResultSet as per review comments.

Therefore, there are two improvements that are required from the core part at the moment:
1. Schema propagation
1. Expected result type propagation

@Holmistr could you please add these two points to the SQL client PRD?

2020-12-08 08:57 UTC, SeriyBg commented on src/main/java/com/hazelcast/jdbc/JdbcConnection.java
> +        checkClosed();
Wouldn't it be the best option to throw an unsupported exception?
Ignoring them will be confusing for the users, so we might eighter pass through or throw an unsupported exception

2020-12-08 08:59 UTC, SeriyBg commented on src/main/java/com/hazelcast/jdbc/JdbcConnection.java
> +        checkClosed();
Well, the JavaDoc says that the method should throw `SQLFeatureNotSupportedException` if the driver does not support the method. I guess we found the solution 😃

2020-12-08 11:18 UTC, SeriyBg commented on src/main/java/com/hazelcast/jdbc/HazelcastJdbcStatement.java
> +        return false;
Since Jet build is not stable I won't able to test `executeUpdate` so would suggest having it in the next PR, so that this one won't become in the pending state for too long

2020-12-08 16:25 UTC, SeriyBg commented on pom.xml
> +      <version>${hazelcast.version}</version>
Moved it to the `test` scope, since it's used for the unit testing

2020-12-09 07:03 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/HazelcastJdbcStatement.java
> +        return false;
We fixed the Jet build yesterday evening. Hopefully, it should become stable today.

2020-12-11 08:48 UTC, devozerov commented on pom.xml
> +            <scope>provided</scope>
Is there a reason why we declare the `hazelcast` dependency as provided? Consider that a user would like to add the JDBC driver to a Maven project. Will he require to add `hazelcast-jdbc` only, or both `hazelcast-jdbc` and `hazelcast`? If the latter, I would propose to change the dependency definition to `compile`, unless there is a reason for not doing so.

2020-12-11 08:55 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/Driver.java
> +            throw new SQLException("URL " + url + " is not supported");
Looks like this is not in line with the standard. From JavaDoc: "The driver should return "null" if it realizes it is the wrong kind of driver to connect to the given URL."

2020-12-11 08:55 UTC, SeriyBg commented on pom.xml
> +            <scope>provided</scope>
Agree, since there is no reason for using `hazelcast-jdbc` without `hazelcast`

2020-12-11 08:57 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/Driver.java
> +    private URI pareUrl(String url) throws SQLException {
Unused method

2020-12-11 09:01 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/HazelcastJdbcClient.java
> +package com.hazelcast.jdbc;
In IMDG there is a rule that public API classes and private classes are located in separate packages, e.g. `com.hazelcast.map` for public IMap API, `com.hazelcast.map.impl` for the internal implementation. 
Are there similar rules for clients/integrations? If yes, we should keep the driver and JDBC objects (connection, statement, prepared statement, result set) public, since they could be accessed through the `unwrap` call, and move the rest classes to `com.hazelcast.jdbc.impl`.

2020-12-11 09:03 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/JdbcUrl.java
> +import java.util.Arrays;
Unused import. Perhaps, the `checkstyle` plugin integration is needed to avoid this kind of problem. Are `checkstyle` and `spotbugs` plugins used by the integration team?

2020-12-11 09:07 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/JdbcConnection.java
> +            throw new SQLException("Connection is closed", "STATE", -1);
SQL STATE and vendor could not be chosen arbitrary, since SQLSTATE codes are part of the JDBC standard, and vendor code is a part of public API. We should either develop our code system right away (e.g. see `SqlErrorCode` in the IMDG code base), or ignore it for now and do it in a separate ticket. If we chose the latter approach, it is better to avoid setting explicit SQLSTATE and vendor codes for now and instead call `SQLException` constructors that set the default values.

2020-12-11 09:08 UTC, SeriyBg commented on src/main/java/com/hazelcast/jdbc/JdbcUrl.java
> +import java.util.Arrays;
Yes, they are. Will add them to the project

2020-12-11 09:11 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/JdbcConnection.java
> +    public boolean isValid(int timeout) throws SQLException {
The `isValid` method should not call `checkClosed`.

2020-12-11 09:15 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/JdbcConnection.java
> +        return null;
`createSQLXML` should throw an unsupported exception

2020-12-11 09:15 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/JdbcConnection.java
> +        return null;
`createBlob` should throw an unsupported exception

2020-12-11 09:16 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/JdbcConnection.java
> +class JdbcConnection implements Connection {
Since this class is part of public API, it is better to follow a common naming scheme. E.g. either add the `Hazelcast` prefix to it or remove the `Hazelcast` from the statement, prepared statement, and result set objects.

2020-12-11 09:18 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/JdbcConnection.java
> +        checkClosed();
The comment above is not addressed - the method should throw an exception if the passed value is not one of the predefined constants.

2020-12-11 09:23 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/JdbcConnection.java
> +    public Properties getClientInfo() throws SQLException {
I still have doubts about the implementation of `get/setClientInfo` methods. Is it ok to return `null` from them? Could `null` break some integrations? We may take a look at other mature drivers to get some sense of how this should be implemented, e.g. https://github.com/pgjdbc/pgjdbc

I propose to create a separate ticket for this, that should be addressed before the initial release.

2020-12-11 09:28 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/JdbcConnection.java
> +    public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
General comment for createStatement and prepareStatement methods that accept `autoGeneratedKeys`, `columnIndexes`, `columnNames`, and `resultSetType/resultSetConcurrency/resultSetHoldability` - we should not fail them blindly. Every such a method contains a combination of parameters that allow us to execute the query still. For example:
1. `prepareStatement(String sql, int autoGeneratedKeys)` is perfectly valid for us if `autoGeneratedKeys=Statement.NO_GENERATED_KEYS`
1. Likewise, `prepareStatement(String sql, int[] columnIndexes)` is valid if `columnIndexes` is an array of length zero

And so on. We do not know which exact methods will be used by the external tools. Therefore, we need to ensure that as many methods work as possible under different combinations of parameters.

2020-12-11 09:39 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/HazelcastJdbcStatement.java
> +    public ResultSet executeQuery(String sql) throws SQLException {
The `executeQuery` method should throw an exception if the produced result is not a `result set`, or if it is called on an instance of `PreparedStatement`.

2020-12-11 09:39 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/HazelcastJdbcStatement.java
> +    public int executeUpdate(String sql) throws SQLException {
The `executeUpdate` method should throw an exception if the produced result is a result set, or if it is called on an instance of `PreparedStatement`.

2020-12-11 09:40 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/HazelcastJdbcStatement.java
> +        checkClosed();
The method should check if the `max` argument is non-negative.

2020-12-11 09:43 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/HazelcastJdbcStatement.java
> +        checkClosed();
The `setFetchSize` method should validate `rows` argument as per JavaDoc.

2020-12-11 09:45 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/HazelcastJdbcStatement.java
> +    public ResultSet getGeneratedKeys() throws SQLException {
This method might return an empty result set rather than throwing an exception. The less our methods throw an exception - the better.

2020-12-11 09:46 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/HazelcastJdbcStatement.java
> +    public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
Similarly to the comment in the `Connection` object - we should not necessarily throw an exception from the non-default `execute*` method. The exception should be thrown only if the passed parameters are unsupported.

2020-12-11 09:49 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/HazelcastJdbcStatement.java
> +            close();
It seems that the implementation of this method may lead to mutual calls of the `close` methods as follows:
`ResultSet.close -> Statement.close -> ResultSet.close`?

2020-12-11 09:58 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/HazelcastJdbcPreparedStatement.java
> +        parameters.add(parameterIndex - 1, parameter);
The implementation of this method is incorrect - it will throw an exception in many situations because we do not ensure that the list has sufficient capacity. We should check the list size first, and if it is not sufficient - expand it. Also, this indicates that there are not enough tests for parameters.

Another problem is that there is no check for parameter index (it should be positive).

Last, how to deal with an incomplete parameter list? Suppose that a user has a query `SELECT ... WHERE ? = ?`. There are two parameters. What should happen if the user did `setParameter(2, ...)`, but didn't do `setParameter(1, ...)`. Perhaps, we should throw an exception in this case.

2020-12-11 10:02 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/HazelcastJdbcPreparedStatement.java
> +    public void setObject(int parameterIndex, Object x, int targetSqlType, int scaleOrLength) throws SQLException {
It seems that the proper implementation should perform conversion as per the target type. We should either understand in detail how to implement this method properly or do this in a separate issue. In the latter case, it is better to throw an unsupported exception here. The same is applicable to the `setObject(int parameterIndex, Object x, int targetSqlType)` method.

2020-12-11 10:03 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/HazelcastJdbcPreparedStatement.java
> +        return null;
We should throw an exception here rather than throwing an exception. Perhaps the proper implementation of this method will require changes to the client protocol.

2020-12-11 10:03 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/HazelcastJdbcPreparedStatement.java
> +        checkClosed();
`setURL` ignores the passed value. Should we throw an exception here?

2020-12-11 10:04 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/HazelcastJdbcPreparedStatement.java
> +        checkClosed();
`setDate/setTime/setTimestamp` are not implemented.

2020-12-11 10:05 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/HazelcastJdbcPreparedStatement.java
> +        return null;
The metadata is available from the `SqlResult` object. We'd better implement it ASAP to ensure that no changes to the client protocol are needed. It could be done in a separate issue for sure. But we should not return `null` here, better throw an exception.

2020-12-11 10:06 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/HazelcastJdbcPreparedStatement.java
> +    public void setObject(int parameterIndex, Object x, int targetSqlType, int scaleOrLength) throws SQLException {
Note that these two methods have the default implementations, that throw an unsupported exception. Probably we should just remove our implementations and rely on the defaults.

2020-12-11 10:11 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/HazelcastJdbcPreparedStatement.java
> +    public void setDate(int parameterIndex, Date x) throws SQLException {
We should be very careful with `setDate/Time/Timestamp methods`. They refer to `DATE/TIME/TIMESTAMP` types in the SQL standard. Therefore, we must convert passed values to `LocalDate/LocalTime/LocalDateTime` taking in count user timezone somehow. Perhaps date/time/timezone handling worth a separate ticket, since it is complicated and will require many tests.

2020-12-11 10:12 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/HazelcastJdbcPreparedStatement.java
> +        checkClosed();
The `executeQuery`/`executeUpdate` methods should throw an exception if the type of the result is not as expected.

2020-12-11 10:16 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/HazelcastJdbcResultSet.java
> +        T result = currentCursorPosition.getObject(columnLabel);
This comment is not addressed. It doesn't make sense to review the class, since the implicit conversions are the foundational part of the `ResultSet` implementation. We have a set of type converters in IMDG in the `com.hazelcast.sql.impl.type.converter` package. These converters already take into count necessary restrictions (such as out of range conditions).  Perhaps they will solve most of the issues, with exception of temporal types conversions (date, time, timestamp) that require separate careful implementation.

2020-12-11 10:20 UTC, devozerov commented
I conducted the second round of review. Still plenty of things to address. The most complicated are:
1) Type conversations in the `ResultSet` implementation - this is a big thing that is a must for the initial implementation and requires very careful testing
2) Management of the temporal types

To keep the process under the control, we may move many of the comments to separate issues. This will simplify the implementation and review process. But generally, we should not commit to master something that is definitively broken. For example, type conversions are not implemented at the moment. We may implement them in a separate ticket, but in this case, this PR should throw proper exceptions in the case of a type mismatch.

2020-12-11 10:28 UTC, SeriyBg commented
@devozerov thanks for the review.
I would prefer to move as much as possible to a separate PR so that this one doesn't become too big. I will add the proper validation and exception for those issues.

2020-12-11 10:34 UTC, SeriyBg commented on src/main/java/com/hazelcast/jdbc/HazelcastJdbcClient.java
> +package com.hazelcast.jdbc;
There is no such rule in the integration team, so I have made the internal classes package-private that should be enough for now, since the project quite small

2020-12-11 16:23 UTC, SeriyBg commented on src/main/java/com/hazelcast/jdbc/HazelcastJdbcPreparedStatement.java
> +    public void setObject(int parameterIndex, Object x, int targetSqlType, int scaleOrLength) throws SQLException {
The default implementation is there for the `setObject` overloaded method, so we cannot simply remove this implementation, so it's better to throw an exception for now

2020-12-11 17:00 UTC, SeriyBg commented on src/main/java/com/hazelcast/jdbc/HazelcastJdbcPreparedStatement.java
> +        parameters.add(parameterIndex - 1, parameter);
For the parameters list, we are using `ArrayList` so the capacity check is redundant as it will expand automatically.
But for paramIndex and incomplete param list, the validation will add

2020-12-14 15:29 UTC, SeriyBg commented
@devozerov checkstyle and spotbugs I will add as a separate PR so that this one won't become huge

2020-12-15 12:17 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/ParameterList.java
> +        int parametersNumber = Math.toIntExact(sql.chars().filter(c -> c == '?').count());
This is an extremely unreliable way to get the number of parameters, because `?` could be in string literals. We should not use it.  Instead, it is better to grow the list to match the required number of parameters dynamically.

2020-12-15 12:18 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/ParameterList.java
> +    private static class Parameter {
Generally, the null-check is possible without a wrapper. We may use `NULL = new Object()` as a null-marker.

2020-12-15 12:19 UTC, SeriyBg commented on src/main/java/com/hazelcast/jdbc/ParameterList.java
> +    private static class Parameter {
Wouldn't it be less obvious then?

2020-12-15 12:23 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/JdbcConnection.java
> +    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
We do not support all result set modes. For example, for `resultSetType` we support only `TYPE_FORWARD_ONLY`, and for `resultSetConcurrency` we support only `CONCUR_READ_ONLY`.

Two fixes are required in methods the work with these parameters:
1. Validation of passed values as per JavaDoc
1. Throw an exception if `resultSetType != TYPE_FORWARD_ONLY` or `resultSetConcurrency != CONCUR_READ_ONLY`

2020-12-15 12:26 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/JdbcStatement.java
> +package com.hazelcast.jdbc;
We should add file headers with our license to all our classes.

2020-12-15 12:27 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/JdbcStatement.java
> +        checkClosed();
`setMaxFieldSize` requires validation of the passed parameter as per JavaDoc

2020-12-15 12:29 UTC, Holmistr commented
Just got to this PR as I was notified previously:
```
Therefore, there are two improvements that are required from the core part at the moment:

    Schema propagation
    Expected result type propagation

@Holmistr could you please add these two points to the SQL client PRD?
```

Yes, I will add it to the document.

2020-12-15 12:33 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/JdbcStatement.java
> +        if (this instanceof PreparedStatement) {
Check for prepared statement is added after the actual query is executed, which makes it useless. Instead, it is better to override this method in the `PreparedStatement` and throw an exception right away. Same for executeUpdate() and execute() methods.

2020-12-15 12:33 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/JdbcStatement.java
> +        doExecute(sql, Collections.emptyList());
We are leaking the opened `ResultSet` here since it is not closed.

2020-12-15 12:37 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/JdbcStatement.java
> +        doExecute(sql, Collections.emptyList());
Perhaps it is better to add the expected result type to the `doExecute` method (e.g., RESULT_SET, UPDATE_COUNT, ANY), and perform the proper cleanup there. This way we will not have to bother about the behavior in 6 `execute` methods from `Statement` and `PreparedStatement` classes.

2020-12-15 12:38 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/JdbcPreparedStatement.java
> +        doExecute(sql, parameters.asParameters());
The check for a returned result type is missing.

2020-12-15 12:38 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/JdbcPreparedStatement.java
> +        doExecute(sql, parameters.asParameters());
The check for a returned result type is missing.

2020-12-15 12:44 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/JdbcResultSet.java
> +        return getBigDecimal(columnLabel).setScale(scale, BigDecimal.ROUND_UNNECESSARY);
This method is marked as deprecated. It seems we throw "unsupported" from here instead.

2020-12-15 12:44 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/JdbcResultSet.java
> +        return getBigDecimal(columnIndex).setScale(scale, BigDecimal.ROUND_UNNECESSARY);
This method is marked as deprecated. It seems we throw "unsupported" from here instead.

2020-12-15 12:48 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/JdbcResultSet.java
> +        return sqlResult.getRowMetadata().findColumn(columnLabel);
The method should throw an exception if the column is not found. In the current implementation, it will return -1.

2020-12-15 12:50 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/JdbcResultSet.java
> +        T result = currentCursorPosition.getObject(columnLabel);
We cannot use `SqlRow.getObject(String)` here because it will throw an `IllegalArgumentException` here instead of `SQLException`. Instead, we should look up the column index, and if it is valid - do a row column lookup via index.

2020-12-15 12:52 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/JdbcResultSet.java
> +        T result = currentCursorPosition.getObject(columnIndex);
`SqlRow.getObject(int)` is zero-based, while `ResultSet` is 1-based. Therefore, we do a lookup over an invalid index. If we didn't catch this in tests, then the test coverage is not sufficient. We need to plan the exhaustive testing of all methods before the initial release.

2020-12-15 12:59 UTC, devozerov commented
I conducted another round of reviews. Please take into count the following considerations:
1. Checkstyle is not integrated, so we miss big things such as missing licenses. Please decide how and when to integrate the check style.
1. Test coverage appears to be grossly insufficient. We may do it in separate PRs for sure, but it should be planned before 4.2 release.
1. We have a number of other important things to address in separate PRs, such as temporal types support, implicit conversions, etc. We need a way to ensure that we do not miss them. My proposal is to create relevant issues and assign them to 4.2 milestones before merging this PR. Alternatively, we may put special TODOs in the code, etc. Otherwise, we are risking to miss big problems when doing a release. 

@SeriyBg @leszko @Holmistr since the things mentioned above is more about the development process, and I do not know how it is organized in the integrations team, please discuss it internally what needs to be done to ensure that we do not miss them before doing the 4.2 release.

2020-12-15 13:01 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/ParameterList.java
> +    private static class Parameter {
It's a minor thing, both ways work.

2020-12-15 15:12 UTC, SeriyBg commented on src/main/java/com/hazelcast/jdbc/ParameterList.java
> +        int parametersNumber = Math.toIntExact(sql.chars().filter(c -> c == '?').count());
Indeed, the string literals containing `?` would be considered as a parameter for this case. But we should also validate the case when not all the parameters are set. I Will think about the solution

2020-12-16 09:05 UTC, SeriyBg commented
@devozerov thank you for the review!

Checkstyle and findbugs are available at https://github.com/hazelcast/hazelcast-jdbc/tree/checkstyle that is based on the current branch. I will create the PR later when this one is merged.

For the issues that need to be addressed before the release, I have created GH issues and assigned them to the 4.2 Milestone, as you've suggested.

2020-12-16 09:11 UTC, pivovarit commented on src/main/java/com/hazelcast/jdbc/Driver.java
> +    /** Major version. */
Not sure if these comments are useful enough :)

2020-12-16 09:15 UTC, leszko commented
Please see my comments.

> 1. Checkstyle is not integrated, so we miss big things such as missing licenses. Please decide how and when to integrate the checkstyle.

We should integrate checkstyle the same way we do for other projects. We have it in every module, so it should be just copy-paste. The same with CI with GH Actions, setting dependbot, setting codeowners. It's way better to do it upfront. A separate PR is ok, but in general these should be the first things to set up when starting a new project.

> 2. Test coverage appears to be grossly insufficient. We may do it in separate PRs for sure, but it should be planned before 4.2 release.

We should strive for high test coverage. I know 100% is not always achievable, but something like 80-90% should be the minimum. Unless there is a clear reason for not providing such coverage.

> 3. We have a number of other important things to address in separate PRs, such as temporal types support, implicit conversions, etc. We need a way to ensure that we do not miss them. My proposal is to create relevant issues and assign them to the 4.2 milestone before merging this PR. Alternatively, we may put special TODOs in the code, etc. Otherwise, we are risking to miss big problems when doing a release.

Please create GH Issues with the `4.2` milestone and mention it in the PRD. We need to have these points in PRD (you can just create a requirement with GH issue links) as well to not forget about them.

2020-12-16 09:25 UTC, pivovarit commented on src/main/java/com/hazelcast/jdbc/JdbcResultSet.java
> +        return wasNull;
Can this be set/read by multiple threads?

2020-12-16 09:30 UTC, pivovarit commented on src/main/java/com/hazelcast/jdbc/JdbcStatement.java
> +package com.hazelcast.jdbc;
btw, this can be set in IDEA and then you no longer need to worry about that (+ checkstyle check_

2020-12-16 09:39 UTC, pivovarit commented on src/main/java/com/hazelcast/jdbc/JdbcStatement.java
> +    int updateCount = -1;
_-1_ is a magic number

2020-12-16 09:40 UTC, SeriyBg commented on src/main/java/com/hazelcast/jdbc/JdbcResultSet.java
> +        return wasNull;
afaik, ResultSet is not usually shared between the threads

2020-12-16 09:43 UTC, pivovarit commented on src/main/java/com/hazelcast/jdbc/JdbcResultSet.java
> +        return wasNull;
And what's more, it should not be. I double-checked.

2020-12-16 09:49 UTC, pivovarit commented on src/main/java/com/hazelcast/jdbc/JdbcConnection.java
> +        throw JdbcUtils.unsupported("CallableStatement not supported");
Shouldn't it just throw an unsupported exception regardless of the fact if the _JdbcConnection_ is closed or not?

2020-12-16 09:55 UTC, SeriyBg commented on src/main/java/com/hazelcast/jdbc/JdbcConnection.java
> +        throw JdbcUtils.unsupported("CallableStatement not supported");
I don't think there is one correct answer here, but from my PoV, if the Connection/Statement/ResultSet is closed, it's better to inform the user ASAP

2020-12-16 10:05 UTC, pivovarit commented on src/main/java/com/hazelcast/jdbc/JdbcConnection.java
> +        throw JdbcUtils.unsupported("CallableStatement not supported");
Have you checked other implementations? when implementing standards, it's more important to conform even if it means doing something against what we perceive as "better"

2020-12-16 10:22 UTC, SeriyBg commented on src/main/java/com/hazelcast/jdbc/ParameterList.java
> +        int parametersNumber = Math.toIntExact(sql.chars().filter(c -> c == '?').count());
This issue seems to require a complex `SQL` parsing, thus I have moved it to a separate issue #9 assigned to the 4.2 Milestone so that it can be addressed in a separate PR but will be present in the initial release

2020-12-16 10:25 UTC, SeriyBg commented on src/main/java/com/hazelcast/jdbc/JdbcConnection.java
> +        throw JdbcUtils.unsupported("CallableStatement not supported");
Looking into H2 I can see that they are just throwing the unsupported exception. Will change it to follow the same rule here

2020-12-16 14:18 UTC, pivovarit commented on src/main/java/com/hazelcast/jdbc/JdbcConnection.java
> + * http://www.apache.org/licenses/LICENSE-2.0
@jerrinot Any idea which license should `hazelcast-jdbc` use?

2020-12-16 14:26 UTC, pivovarit commented on src/main/java/com/hazelcast/jdbc/JdbcConnection.java
> +    public Properties getClientInfo() throws SQLException {
Perhaps, we should just return an empty `Properties` object?

2020-12-16 14:33 UTC, pivovarit commented on src/main/java/com/hazelcast/jdbc/JdbcResultSet.java
> +            closing = true;
Do we really need the second flag? `ResultSet` is not supposed to be thread-safe and it looks like _closing_ is used only in this place.

2020-12-16 14:38 UTC, SeriyBg commented on src/main/java/com/hazelcast/jdbc/JdbcResultSet.java
> +            closing = true;
We do because ResultSet calls `statment.tryCloseOnCompletion` which will call `resultSet.close()` which might result in endless recurring call and SO

2020-12-17 14:36 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/ParameterList.java
> +        int parametersNumber = Math.toIntExact(sql.chars().filter(c -> c == '?').count());
I am not sure I agree with this. This way we will merge the code that is definitively broken. Parameter validation is already handled properly in the SQL backend, so there is no need to parse anything on the client-side. The only thing that is required from JDBC, is to detect the case when the list of parameters is not continuous. 

For example, this code is valid:
```
setInt(1, VAL_1);
setInt(2, VAL_2);
execute();
```
Produces the valid continuous list of parameters `[VAL_1, VAL_2]`. We may send them to the server right away. If the actual number of parameters is different, the server will throw an exception.

To contrast, the following code is invalid:
```
setInt(2, VAL_2);
execute();
```
It produces a non-continuous list of parameters `[UNSET, VAL_2]`. We do not know which value to pass for the first parameter - should it be null? or should it be zero? or something else? To avoid undefined behavior, we may throw an exception right away.

2020-12-17 14:44 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/JdbcStatement.java
> +                throw new SQLException("Invalid SQL statement");
I would propose to make the error messages more concrete. For example "Statement produced update count" and "Statement produced result set", or so. Otherwise, it is not very clear why the statement is invalid.

2020-12-17 14:46 UTC, devozerov approved these changes
Approving with two outstanding comments that I propose to fix before merge:
1. It is better to improve the error message for the invalid result types in the `JdbcStatement` class
2. Parsing for parameter placeholders is not needed on the client-side (see the comment in the `ParameterList` class)

2020-12-17 15:59 UTC, SeriyBg commented on src/main/java/com/hazelcast/jdbc/ParameterList.java
> +        int parametersNumber = Math.toIntExact(sql.chars().filter(c -> c == '?').count());
Yes, but in this case, the exception will be handled only after the `execute()` method is called. However, `JavaDoc` of `set<Type>` states:

```
@exception SQLException if parameterIndex does not correspond to a parameter marker in the SQL statement;
```

So if don't rely on the existing backend for parameters check we will violate this validation, for the SQL `SELECT * FROM foo WHERE bar = ?` the following code will not throw any exception until `execute()` method is called:

```
setInt(1, VAL_1);
setInt(2, VAL_2);
```

2020-12-17 16:34 UTC, SeriyBg commented on src/main/java/com/hazelcast/jdbc/ParameterList.java
> +        int parametersNumber = Math.toIntExact(sql.chars().filter(c -> c == '?').count());
I would suggest applying the change that you have suggested, as this is the better of two evils, however, I think that issue #9 should be implemented

2020-12-18 08:31 UTC, pivovarit approved these changes

2020-12-18 08:32 UTC, merged