Add ResultSet Metadata support
hazelcast/hazelcast-jdbc pull request #20
Opened 2021-01-04 08:43 UTC by SeriyBg

Fix #7

2021-01-04 08:54 UTC, pivovarit commented
```
Error:    DriverJetTest.beforeAll:53 ExceptionInInitializer
```

Doesn't look fixed to me :)

2021-01-04 09:20 UTC, SeriyBg commented
> ```
> Error:    DriverJetTest.beforeAll:53 ExceptionInInitializer
> ```
> 
> Doesn't look fixed to me :)

Will be ignored for now. I'm using the IMDG API added in 4.2-SNAPSHOT, but Jet uses 4.1.1-SNAPSHOT version. So until Jet updates the dependency it will be broken

2021-01-06 15:58 UTC, pivovarit requested changes

2021-01-06 15:58 UTC, pivovarit commented on src/main/java/com/hazelcast/jdbc/JdbcResultSetMetaData.java
> +        return "";
Since `""` represents the "not applicable" case, I'd store it as constant.

2021-01-06 15:58 UTC, pivovarit commented on src/main/java/com/hazelcast/jdbc/JdbcResultSetMetaData.java
> +        return 0;
Since `0` represents the "not applicable" case, I'd store it as constant.

2021-01-06 15:58 UTC, pivovarit commented on src/main/java/com/hazelcast/jdbc/JdbcResultSetMetaData.java
> +        return 0;
Shouldn't this be a positive number instead?

Docs don't explicitly say to use `0` when not supported.

2021-01-11 16:35 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/JdbcResultSetMetaData.java
> +        return SQL_TYPES_MAPPING.getOrDefault(sqlRowMetadata.getColumn(column).getType(), Types.OTHER);
AFAIU we should never fallback to `OTHER` since we have mappings for all Hazelcast types. In this case, I would rather add an assertion that `SQL_TYPES_MAPPING.get` returns a non-null value, rather than fallback to the `OTHER` type.

2021-01-11 16:37 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/JdbcResultSetMetaData.java
> +    public int getPrecision(int column) {
`precision/scale` should be implemented for those types that support it (e.g., numeric types).

2021-01-11 16:38 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/JdbcResultSetMetaData.java
> +        return schema;
The returned schema is the schema of the table's column, not the current schema. Since we do not expose such information now, we should return `""` here.

2021-01-11 16:40 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/JdbcResultSetMetaData.java
> +        return 0;
I believe we should define some constants for our types. AFAIK this method is used by tools to determine how much space to dedicate to the column's value on the screen (either in console or UI application).

2021-01-11 16:40 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/JdbcResultSetMetaData.java
> +        return false;
Our numeric types are signed.

2021-01-12 08:55 UTC, SeriyBg commented on src/main/java/com/hazelcast/jdbc/JdbcResultSetMetaData.java
> +        return SQL_TYPES_MAPPING.getOrDefault(sqlRowMetadata.getColumn(column).getType(), Types.OTHER);
Should we throw `SQLException` if it does? The JavaDoc doesn't explicitly say that exception will be thrown in this case

2021-01-12 11:57 UTC, SeriyBg commented on src/main/java/com/hazelcast/jdbc/JdbcResultSetMetaData.java
> +    public int getPrecision(int column) {
AFAIU, the values for `precision/scale` are usually defined during the column declaration, but for our case, we don't have this declaration, and we can store different `precision/scale` values for different rows. Should we have some sort of static table with the default value for each type, as the `SQL API` does provide this info?

2021-01-12 12:56 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/JdbcResultSetMetaData.java
> +    public int getPrecision(int column) {
Yes, we should just expose some static information. For integer types, this is the number of digits. For `DECIMAL`, the precision/scale could be 38 (this is what we use in Apache Calcite). For strings, we assume possibly very long values, so we may set 2000 (again, this is what we use in Apache Calcite).

2021-01-12 12:58 UTC, devozerov commented on src/main/java/com/hazelcast/jdbc/JdbcResultSetMetaData.java
> +        return SQL_TYPES_MAPPING.getOrDefault(sqlRowMetadata.getColumn(column).getType(), Types.OTHER);
Generally, this should never happen. So maybe even an assertion will suffice. If we want to throw something, then we may throw an `SQLException`, since it is already part of the API.

2021-01-15 10:25 UTC, devozerov approved these changes

2021-01-18 08:55 UTC, merged