Change cloud config placement to allow SSL usage
hazelcast/hazelcast-jdbc pull request #201
Opened 2022-10-17 11:35 UTC by Fly-Style

2022-10-17 11:36 UTC, Fly-Style commented
@neilstevenson also take a look, please, if I understood you correctly.

2022-10-17 11:37 UTC, Fly-Style commented
Closes #168, #200

2022-10-21 09:00 UTC, viliam-durina requested changes

2022-10-21 09:00 UTC, viliam-durina commented on src/main/java/com/hazelcast/jdbc/HazelcastConfigFactory.java
>          return clientConfig;
The code flow in this method is messy. It calls `securityConfig` to create the initial ClientConfig. Then it might call `cloudConfig()` method and return its return value, even though it returns the same clientConfig instance.

I think it would be easier to read if this method created the `clientConfig` at the beginning, then called some methods to modify it (`securityConfig`, `cloudConfig`) and then return the local variable.

2023-02-06 07:38 UTC, closed without merging