Update README.md with more Viridian details
hazelcast/hazelcast-jdbc pull request #245
Opened 2023-03-16 13:23 UTC by EugeneAbramchuk

Add missing SSL configuration properties and provided samples

2023-03-16 15:56 UTC, angelasimms requested changes

2023-03-16 15:56 UTC, angelasimms commented on README.md
> +If you're connecting to [Hazelcast Viridian](https://viridian.hazelcast.com/), also specify `cloudUrl=https://api.viridian.hazelcast.com` and `sslEnabled=true`: `jdbc:hazelcast://<cluster-name>/?disc
```suggestion
If you're connecting to a [Viridian Serverless cluster](https://viridian.hazelcast.com/), also specify `cloudUrl=https://api.viridian.hazelcast.com` and `sslEnabled=true`: `jdbc:hazelcast://<cluster-name>/?discoveryToken=<yourDiscoveryToken>&cloudUrl=https://api.viridian.hazelcast.com&sslEnabled=true`. 
```

2023-03-16 15:56 UTC, angelasimms commented on README.md
> +TLS is mandatory for Viridian cluster connections so pass TLS properties such as truststore, keystore etc along to `DriverManager.getConnection()`.
```suggestion
TLS is mandatory for Viridian Serverless cluster connections so pass TLS properties such as truststore, keystore etc along to `DriverManager.getConnection()`.
```

2023-03-16 16:17 UTC, angelasimms approved these changes
LGTM

2023-03-17 13:03 UTC, viliam-durina commented on README.md
> +TLS is mandatory for Viridian Serverless cluster connections so pass TLS properties such as truststore, keystore etc along to `DriverManager.getConnection()`.
I find it confusing that we use SSL and TLS interchangeably. For example, "You should use TLS, therefore specify `sslEnabled`".

```suggestion
SSL is mandatory for Viridian Serverless cluster connections so add SSL properties such as `trustStore`, `keyStore` etc. in the URL.
```

2023-03-17 13:03 UTC, viliam-durina commented on README.md
> +If you're connecting to a [Viridian Serverless cluster](https://viridian.hazelcast.com/), also specify `cloudUrl=https://api.viridian.hazelcast.com` and `sslEnabled=true`: `jdbc:hazelcast://<cluster-
Would be better to refer to the URL above.

2023-03-17 19:00 UTC, EugeneAbramchuk commented on README.md
> +TLS is mandatory for Viridian Serverless cluster connections so pass TLS properties such as truststore, keystore etc along to `DriverManager.getConnection()`.
I think we do not support SSL now at all, so TLS is a better name. The query parameter actually seems to be a misnomer which should be renamed to `tlsEnabled`.

2023-04-10 12:54 UTC, EugeneAbramchuk commented on README.md
>  jdbc:hazelcast://cluster-id/discoveryToken=value[&property1=value1[&property2=value2]...]
It is closer to cluster id indeed, and has a `pr-` prefix. I updated all details correspondingly.

2023-04-19 11:16 UTC, k-jamroz approved these changes

2023-04-19 11:17 UTC, merged