WIP
hazelcast/hazelcast-jdbc pull request #271
Opened 2023-07-31 13:25 UTC by sumnerib

2023-08-02 06:15 UTC, kwart requested changes
I like the improvement, just left some comments.
I didn't know about the possibility of using container services, so happy to learn sth new :+1:

2023-08-02 06:15 UTC, kwart commented on .github/workflows/deploy-release.yml
> +        image: hazelcast/hazelcast
This should be faster:
```suggestion
        image: hazelcast/hazelcast:latest-slim
```

2023-08-02 06:15 UTC, kwart commented on .github/workflows/deploy-release.yml
> +        image: hazelcast/hazelcast-enterprise
```suggestion
        image: hazelcast/hazelcast-enterprise:latest-slim
```

2023-08-02 06:17 UTC, kwart commented
BTW When you have EE and OS hazelcast members as services, don't they try to connect one to the other?

2023-08-02 08:18 UTC, nishaatr commented on .github/workflows/deploy-release.yml
> +        timeout-minutes: 2
Is 2mins enough? 
Is timeout needed as I would expect calls to HZ will or should fail
Trying to understand the reason behind the timeout?

2023-08-02 08:18 UTC, nishaatr commented on smoke-test/src/main/java/com/hazelcast/smoke/test/SmokeTestDriver.java
> +                assert insertCount == 0;
I agree with Josef considering try() is in use

2023-08-02 08:24 UTC, nishaatr commented on smoke-test/src/main/java/com/hazelcast/smoke/test/SmokeTestDriver.java
> +                assert insertCount == 0;
Any reason for the top smoke-test folder?

We have this test folder https://github.com/hazelcast/hazelcast-jdbc/tree/360f04b177e6592f3089f5322943c321c88c2f72/hazelcast-jdbc-core/src/test/java/com/hazelcast/jdbc

2023-08-02 08:27 UTC, nishaatr commented on smoke-test/src/main/java/com/hazelcast/smoke/test/SmokeTestDriver.java
> +                assert insertCount == 0;
Normally test files end with *Test.java
Not a issue but perhaps just SmokeTest.java?

2023-08-02 08:56 UTC, kwart commented on smoke-test/src/main/java/com/hazelcast/smoke/test/SmokeTestDriver.java
> +                assert insertCount == 0;
I have no strong opinion on the location (existing or new module) - both sounds OK.
WRT the class name, I like the original `SmokeTestDriver` more. The `*Test` ones are usually unit tests you want to be executed by Maven automatically.

2023-08-02 12:14 UTC, nishaatr commented on smoke-test/src/main/java/com/hazelcast/smoke/test/SmokeTestDriver.java
> +                assert insertCount == 0;
Lets keep as is 
I didn't realize this is a module (I see a POM.xml). Tbh I struggle a little with reviewing GH PRs as not a huge fan of the interface :)

2023-08-02 12:22 UTC, nishaatr commented on smoke-test/src/main/java/com/hazelcast/smoke/test/SmokeTestDriver.java
> +                assert insertCount == 0;
I presume SmokeTestDriver.java will contain all future new tests which might proliferate the file e.g. you might want to separate or group smoke tests - hence, thought 'Driver' might not ideal 

Also, there is no ability to disable some tests apart from commenting them out like with Unit tests

**Just adding some thoughts here and no action needed.**

2023-08-02 14:04 UTC, sumnerib commented
> BTW When you have EE and OS hazelcast members as services, don't they try to connect one to the other?

@kwart I don't have the logs from the runs on my fork, but I think they do since they have a shared network. I tested in my local docker, and indeed they attempt and fail to join via multicast:

```
2023-08-02 11:37:04,939 [ WARN] [hz.dazzling_gagarin.MulticastThread] [c.h.i.c.i.MulticastService]: [172.17.0.2]:5701 [smoke-test] [5.3.1] Received a JoinRequest with an incompatible binary-format. An old version of Hazelcast may be using the same multicast discovery port. Are you running multiple Hazelcast clusters on this host? (This message will be suppressed for 60 seconds).
```

Even though it didn't cause any issue, I will go ahead and add some config to disable multicast and add cluster names, just to be safe. Good catch!

```
          HZ_CLUSTERNAME: smoke-test
          HZ_NETWORK_JOIN_MULTICAST_ENABLED: false
          HZ_NETWORK_JOIN_TCPIP_ENABLED: true
```

2023-08-02 14:14 UTC, sumnerib commented on smoke-test/src/main/java/com/hazelcast/smoke/test/SmokeTestDriver.java
> +                assert insertCount == 0;
I meant to enable assertions (-ea) in my initial commit. Good catch!

@nishaatr I don't expect we should need to add any new tests to `SmokeTestDriver`. The intent is to encapsulate the most basic DDL and CRUD operations used in SQL. Basically, we want to verify that the artifact generated by maven works (in some basic sense) and the needed/expected dependencies are included in the final jar. New feature testing should continue to be in unit/integration tests.

With this in mind, if you think it should be cleaned up and broken into multiple constructs, I'm happy to make those changes as well.

2023-08-03 11:59 UTC, sumnerib commented on .github/workflows/deploy-release.yml
> +        timeout-minutes: 2
Good question. At first I thought the timeout would be necessary, but it seems redundant and unnecessary thinking about it more. Will remove.

2023-08-03 12:11 UTC, nishaatr approved these changes

2023-08-03 13:03 UTC, merged