Upgrade to Java 11 [HZ-3617]
hazelcast/hazelcast-jdbc pull request #289
Opened 2023-12-06 11:17 UTC by orcunc

Upgrade to Java 11
Upgrade various maven plugins
Upgrade Mockio version
Upgrade Jupiter  version
Fix warnings in unit tests

Jira : https://hazelcast.atlassian.net/browse/HZ-3617

2023-12-12 09:42 UTC, frant-hartm requested changes
Mostly LGTM.

2023-12-12 09:42 UTC, frant-hartm commented on hazelcast-jdbc-core/src/test/java/com/hazelcast/jdbc/JdbcDataBaseMetadataTest.java
> +        Connection connection = DriverManager.getConnection(JDBC_HAZELCAST_LOCALHOST);
Where is this connection closed?

2023-12-12 10:12 UTC, orcunc commented on hazelcast-jdbc-core/src/test/java/com/hazelcast/jdbc/JdbcDataBaseMetadataTest.java
> +        Connection connection = DriverManager.getConnection(JDBC_HAZELCAST_LOCALHOST);
rev : 9a6f973065526d5898a5ddff6812151a9328696d

2023-12-12 10:17 UTC, orcunc commented on .gitattributes
> +*        text eol=lf
I thought having explicit configuration instead of relying on the user's git configuration would be better. User may not have configured his git for automatic line ending.

2023-12-12 11:01 UTC, frant-hartm approved these changes

2023-12-14 14:48 UTC, kwart requested changes

2023-12-14 14:48 UTC, kwart commented on .gitattributes
> +*        text eol=lf
I still think this is wrong. Windows users will see the sources with wrong file-endings in their working tree. At least it's how I understand the explanation in https://git-scm.com/docs/gitattributes

2023-12-15 06:20 UTC, orcunc commented on .gitattributes
> +*        text eol=lf
reverted : de8569bfc3e466feaefe3c69e67f8ede002b7bea

2023-12-15 08:30 UTC, orcunc commented
@kwart I have reverted .gitattributes file

2023-12-15 16:32 UTC, kwart reviewed
One more legacy config caught my eye in POM files.

2023-12-15 16:32 UTC, kwart commented on pom.xml
> +        <maven.compiler.target>11</maven.compiler.target>
```suggestion
        <maven.compiler.release>11</maven.compiler.release>
```

2023-12-15 16:32 UTC, kwart commented on smoke-test/pom.xml
> +        <maven.compiler.target>11</maven.compiler.target>
```suggestion
        <maven.compiler.release>11</maven.compiler.release>
```

2023-12-16 08:48 UTC, orcunc commented
@kwart applied suggested maven compiler changes

2023-12-18 09:19 UTC, ldziedziul approved these changes

2023-12-18 09:19 UTC, ldziedziul commented on hazelcast-jdbc-core/pom.xml
> +            <artifactId>junit-jupiter</artifactId>
👍

2023-12-18 13:48 UTC, kwart approved these changes

2023-12-18 13:49 UTC, merged