Configs
hazelcast/hazelcast-jdbc pull request #39
Opened 2021-02-11 14:57 UTC by SeriyBg

2021-02-13 11:42 UTC, viliam-durina reviewed
We ignore unknown properties in the JDBC URL. This is error-prone for the users, but also easier to use. We should check what others do and follow that.

2021-02-13 11:42 UTC, viliam-durina commented on src/main/java/com/hazelcast/jdbc/HazelcastConfigFactory.java
> +        });
This seems wrong to me. Shouldn't we `decode` the keys and values when parsing? Here we decode only the property value. Keys are ascii, but if we accept the URL format, we should accept it anywhere in the url, including in the host name. 
```java
        URI uri = new URI("jdbchazelcast://loc%61lhost:5701/public?a=b");
        System.out.println("protocol:" + uri.getScheme());
        System.out.println("authority:" + uri.getAuthority());
        System.out.println("host:" + uri.getHost());
        System.out.println("port:" + uri.getPort());
        System.out.println("path:" + uri.getPath());
        System.out.println("queryString:" + uri.getQuery());
```
prints:
```
protocol:jdbchazelcast
authority:localhost:5701
host:null
port:-1
path:/public
queryString:a=b
```

Note the `%61` in the hostname. `URI` doesn't like `jdbc:hazelcast`, but that's easy to pre-process. Regarding parsing of the `queryString` we might also look at some util, there might be more dragons lurking... This is also to the topic: https://en.wikipedia.org/wiki/Percent-encoding#Percent-encoding_unreserved_characters

The `UnsupportedEncodingException` is also impossible, but I'd rather re-throw even in that case. You never know... We can also rename `ignored` -> `impossible`

2021-02-15 07:47 UTC, alex-dukhno approved these changes

2021-02-15 07:47 UTC, alex-dukhno commented on src/main/java/com/hazelcast/jdbc/HazelcastConfigFactory.java
> +                .getAwsConfig().setEnabled(true).setUsePublicIp(v.equalsIgnoreCase("true")));
I assume it is because `setUsePublicIp` should be called instead of `setProperty`

2021-02-15 09:36 UTC, SeriyBg commented
> We ignore unknown properties in the JDBC URL. This is error-prone for the users, but also easier to use. We should check what others do and follow that.

@viliam-durina I've checked with the Postgres and MySql Drivers and seems like this is the way to go as they also ignore the unknown properties

2021-02-15 12:39 UTC, SeriyBg commented on src/main/java/com/hazelcast/jdbc/HazelcastConfigFactory.java
> +        });
I'm not sure that we need to add some additional dependencies to the JDBC, but indeed we need to take into consideration this case. As well for the GCP configs, we have a `label` property with the values like `key=value`, so need to support it as well

2021-02-16 16:58 UTC, SeriyBg commented
Current implementation allow for the parameters in the following format `para[key1]=val1&param[key2]=val2`

2021-02-17 13:39 UTC, viliam-durina commented on src/main/java/com/hazelcast/jdbc/HazelcastConfigFactory.java
> +                .getAwsConfig().setEnabled(true).setUsePublicIp(v.equalsIgnoreCase("true")));
I don't get it. Looking at `AwsConfig.setProperty` it handles `"use-public-ip"` property the same way as `setUsePublicIp`.

2021-02-17 14:37 UTC, viliam-durina requested changes

2021-02-17 14:37 UTC, viliam-durina commented on src/test/java/com/hazelcast/jdbc/HazelcastConfigFactoryTest.java
> +                                .setProperty("label", "application=hazelcast,other=value")
We pass this as `&gcpLabel[application]=hazelcast&gcpLabel[other]=value`. Why is the transformation needed? Why can't we directly use `gcpLabel=application%3dhazelcast,other%3dvalue`.

2021-02-17 14:37 UTC, viliam-durina commented on src/main/java/com/hazelcast/jdbc/JdbcUrl.java
> +    private static Map.Entry<String, ParameterValue> parameterValue(String key, String value) {
We don't URL-decode the `key` and the `value`.

2021-02-17 15:39 UTC, SeriyBg commented on src/main/java/com/hazelcast/jdbc/HazelcastConfigFactory.java
> +                .getAwsConfig().setEnabled(true).setUsePublicIp(v.equalsIgnoreCase("true")));
Indeed, looking at the implementation it is the same. Though, in the examples, I've seen that both properties should be set

2021-02-17 16:29 UTC, SeriyBg commented on src/main/java/com/hazelcast/jdbc/HazelcastConfigFactory.java
> +        ClientConfig clientConfig = securityConfig(url, ClientConfig.load());
Usually, JDBC Drivers by themselves don't allow it, additional tools like `Spring` might have such an option. Since hz-client give this option out of the box, why not using it. Do you suggest not to support it?

2021-02-24 14:38 UTC, viliam-durina commented on src/main/java/com/hazelcast/jdbc/HazelcastConfigFactory.java
> +        ClientConfig clientConfig = securityConfig(url, ClientConfig.load());
I don't have a strong opinion. I'm slightly more inclined to not doing it, I don't like when there are 10 ways to configure something. It also depends on the working directory i guess. However if we don't map all the configs, maybe it should be a backdoor to all the options.

2021-02-24 14:39 UTC, viliam-durina commented on src/main/java/com/hazelcast/jdbc/HazelcastConfigFactory.java
> +        });
It's not an additional dependency, it's `java.net.URI`. But now with multiple addresses that's even worse, that's another non-standard part in the JDBC URL.

2021-02-24 14:49 UTC, SeriyBg commented on src/main/java/com/hazelcast/jdbc/HazelcastConfigFactory.java
> +        ClientConfig clientConfig = securityConfig(url, ClientConfig.load());
That's also what I thought. We have the mapping for k8s and cloud properties, but since to have an option for the users to use other configs I think we can reuse the file configs as well (or environment variable)

2021-02-24 14:50 UTC, SeriyBg commented on src/main/java/com/hazelcast/jdbc/HazelcastConfigFactory.java
> +        });
We had a similar discussion with @devozerov previously, and having multiple non-standard parts it was decided not to use `URI`

2021-02-24 14:58 UTC, viliam-durina requested changes

2021-02-24 14:58 UTC, viliam-durina commented on src/main/java/com/hazelcast/jdbc/JdbcUrl.java
> +        String decodedUrl = decodeUrl(url);
This is wrong. You can't url-decode the whole URL, the escaped characters will be used literally, as if not escaped. You have to parse first and then decode the parts.
E.g.
```
jdbc:hazelcast://local%68ost:5701/publi%63?a=%26&b%3d=c
```
Host is `localhost`.
schema is `public`.
Parameter `a` is `&`.
Parameter `b=` is `c`.
You can try with https://www.freeformatter.com/url-parser-query-string-splitter.html

2021-02-24 16:19 UTC, SeriyBg commented on src/main/java/com/hazelcast/jdbc/JdbcUrl.java
> +        String decodedUrl = decodeUrl(url);
You're right. Have fixed it

2021-02-25 08:11 UTC, viliam-durina approved these changes

2021-02-25 09:22 UTC, merged