Connection cache
hazelcast/hazelcast-jdbc pull request #45
Opened 2021-02-25 10:07 UTC by SeriyBg

Reusing existing client instances for the same URL
Fix #24

2021-02-25 10:51 UTC, hakanmemisoglu commented on src/test/java/com/hazelcast/jdbc/JdbcPreparedStatementTest.java
> +    public static void tearDown() {
Do we need a `connection.close()` statement here?

2021-02-25 14:59 UTC, alex-dukhno approved these changes

2021-02-26 11:39 UTC, viliam-durina requested changes

2021-02-26 11:39 UTC, viliam-durina commented on src/main/java/com/hazelcast/jdbc/JdbcUrl.java
> +        return Objects.equals(properties, jdbcUrl.properties) && Objects.equals(rawUrl, jdbcUrl.rawUrl);
I think it's enough to compare the `rawUrl` - it includes the properties.

2021-02-26 11:39 UTC, viliam-durina commented on src/main/java/com/hazelcast/jdbc/HazelcastSqlClient.java
>          client.shutdown();
We close the client with first closed connection, but there can be multiple connections using that same client.

The following test if added to `DriverIMDGTest` fails:
```java
    @Test
    void when_twoConnectionsCreatedAndOneClosed_then_theClientShouldRemain() throws SQLException {
        Connection connection2 = DriverManager.getConnection(JDBC_HAZELCAST_LOCALHOST);
        connection2.close();
        connection.createStatement().execute("SELECT * FROM person");
    }
```
It throws:
```
com.hazelcast.client.HazelcastClientNotActiveException: Client is not active.

	at com.hazelcast.client.impl.clientside.HazelcastClientProxy.getClient(HazelcastClientProxy.java:303)
	at com.hazelcast.client.impl.clientside.HazelcastClientProxy.getSql(HazelcastClientProxy.java:319)
	at com.hazelcast.jdbc.HazelcastSqlClient.execute(HazelcastSqlClient.java:47)
```
We need to do some reference counting.

2021-02-26 12:34 UTC, SeriyBg commented on src/main/java/com/hazelcast/jdbc/JdbcUrl.java
> +        return Objects.equals(properties, jdbcUrl.properties) && Objects.equals(rawUrl, jdbcUrl.rawUrl);
Not always, as the properties might be passed using of the methods `DriverManager.getConnection(String URL, java.util.Properties info)` or `DriverManager.getConnection(String URL, String user, String password)`

2021-02-26 15:10 UTC, viliam-durina commented
There's one more issue with the cached connections: we have to close all results that were created using that connection. E.g.:
```
Connection conn1 = DriverManager.getConnection(...);
Connection conn2 = DriverManager.getConnection(...);
conn1.createStatement().execute(...);
conn2.createStatement().execute(...);
conn1.close();
```
The statement created using `conn1` must be closed (cancelled on server), but the stmt crated using `conn2` must continue.

2021-03-01 09:28 UTC, SeriyBg commented
With the issue mentioned by @viliam-durina it seems that connection caching is an error-prone approach that will unnecessarily complicate the implementation. Thus, for now, I'll close the PR

2021-03-01 09:28 UTC, closed without merging