Multiple minor fixes
hazelcast/hazelcast-jdbc pull request #48
Opened 2021-02-26 22:09 UTC by viliam-durina

2021-03-01 15:52 UTC, SeriyBg requested changes

2021-03-01 15:52 UTC, SeriyBg commented on src/test/java/com/hazelcast/jdbc/ParameterListTest.java
> +class ParameterListTest {
Is this class used anywhere?

2021-03-01 15:52 UTC, SeriyBg commented on src/main/java/com/hazelcast/jdbc/Driver.java
> +        JdbcUrl jdbcUrl;
This seems to violate the specification, as according to the Javadoc: _The driver should return "null" if it realizes it is the wrong kind of driver to connect to the given URL._
But here the `SQLException` will be thrown

2021-03-01 16:42 UTC, viliam-durina commented on src/test/java/com/hazelcast/jdbc/ParameterListTest.java
> +class ParameterListTest {
Looks like a mistake when committing, will fix.

2021-03-01 16:42 UTC, viliam-durina commented on src/main/java/com/hazelcast/jdbc/Driver.java
> +        JdbcUrl jdbcUrl;
Yeah, i didn't read the contract fully, I assumed that the manager calls `acceptsUrl` first before this method. I'll add the check.

2021-03-02 15:07 UTC, SeriyBg approved these changes

2021-03-02 15:59 UTC, merged