add README
hazelcast/hazelcast-jdbc pull request #55
Opened 2021-03-16 16:01 UTC by SeriyBg

2021-03-17 12:35 UTC, devozerov approved these changes

2021-03-17 16:27 UTC, viliam-durina requested changes

2021-03-17 16:27 UTC, viliam-durina commented on README.md
> +**database**: (Required) Hazelcast database name.
I actually don't know what this means. What should I put here? There's no notion of _database_ in hz.

I checked the code, this value is likely ignored. We also call it `schema`. Maybe we should remove it from the URL completely...

2021-03-17 16:27 UTC, viliam-durina commented on README.md
> +| clusterName                    | String  | Hazelcast cluster name |
This seems to be the same thing as the cluster name found in the host name.  If I understand it correctly, if you use `discoverToken`, then the `host` is used as `clusterName` and other properties are ignored, except for `name` and `password`. If there's no `discoverToken`, then the `host` contains the host and other properties are used...

This is confusing. Maybe it would be better to document cloud configuration and host-based configuration separately, including their supported properties.

2021-03-17 16:27 UTC, viliam-durina commented on README.md
> +| k8sServicePort                 | Integer | Endpoint port of the service; if specified with a value greater than 0, it overrides the default; 0 by default |
It might be useful to separate the groups of properties by sub-headers. It might also make it clearer, for example the description of the `keyStore` property, taken out of context, doesn't help me much. If the whole section was named "SSL Options", it would be clearer.

2021-03-17 16:27 UTC, viliam-durina commented on src/test/java/com/hazelcast/jdbc/JdbcUrlTest.java
> +        System.out.println(new JdbcUrl("jdbc:hazelcast://foo/public", null));
What's this test about?

2021-03-17 16:27 UTC, viliam-durina commented on README.md
> +specified using [Overriding Configuration](https://docs.hazelcast.com/imdg/4.2-beta-1/configuration/overriding-configuration-settings)
Shouldn't we also mention that the driver [reads the config file](https://github.com/hazelcast/hazelcast-jdbc/blob/3c3a7d27531b64d8f17366de8bc94b178a9de6dd/src/main/java/com/hazelcast/jdbc/HazelcastConfigFactory.java#L102)? What rules are used to find the file?

2021-03-18 09:17 UTC, SeriyBg commented on src/test/java/com/hazelcast/jdbc/JdbcUrlTest.java
> +        System.out.println(new JdbcUrl("jdbc:hazelcast://foo/public", null));
Opps, that shouldn't have been here 😄

2021-03-18 09:18 UTC, SeriyBg commented on README.md
> +**database**: (Required) Hazelcast database name.
We need a schema, as it is supported by engine, but you are right, it should been called `schema`

2021-03-18 10:57 UTC, viliam-durina commented on README.md
> +**database**: (Required) Hazelcast database name.
Ok, I missed it's used when executing statements. Here we should recommend using `public`.

2021-03-18 10:58 UTC, SeriyBg commented on README.md
> +**database**: (Required) Hazelcast database name.
In what case can it be different from `public`?

2021-03-18 14:46 UTC, alex-dukhno commented on README.md
> +**schema**: (Required) Hazelcast schema name.
do we support schemas? if it always has to be `public` (or what is the default value) maybe it should not be required

2021-03-18 14:50 UTC, SeriyBg commented on README.md
> +**schema**: (Required) Hazelcast schema name.
For the JET it can be different. But it's a topic for discussion

2021-03-18 15:45 UTC, alex-dukhno approved these changes

2021-03-19 16:27 UTC, viliam-durina commented on README.md
> +`hazelcast:4.2`). In the future we plan to support broader client compatibility.
We use `hazelcast-jdbc:4.2` to connect to `hazelcast-jet:4.5` :)

2021-03-19 16:27 UTC, viliam-durina commented on README.md
> +**schema**: (Required) Hazelcast schema name.
As we discussed in slack, I'm for removing the schema from the URL. It's not a connection parameter, can be set with `Connection.setSchema()`

2021-03-19 16:27 UTC, viliam-durina commented on README.md
> +The following list represents the properties supported by the `Hazelcast JDBC Driver`.
```suggestion
The following list contains the properties supported by the `Hazelcast JDBC Driver`.
```

2021-03-19 16:27 UTC, viliam-durina commented on README.md
> +| password                       | String  | Hazelcast client password |
```suggestion
| user                           | String  | Hazelcast cluster username |
| password                       | String  | Hazelcast cluster password |
```

2021-03-19 16:27 UTC, viliam-durina commented on README.md
> +| trustCertCollectionFile        | String  | Path to truststore file |
Description copy-pasted from above line

2021-03-19 16:27 UTC, viliam-durina commented on README.md
> +| keyStore                       | String  | Path of your keystore file |
```suggestion
| keyStore                       | String  | Path to your keystore file |
```

2021-03-19 16:27 UTC, viliam-durina commented on README.md
> +#### AZURE properties
```suggestion
#### Azure properties
```

2021-03-19 16:27 UTC, viliam-durina commented on README.md
> +| azureInstanceMetadataAvailable | Boolean | This property should be configured as `false` in order to be able to use the azure properties. It is `true` by default. |
```suggestion
| azureInstanceMetadataAvailable | Boolean | This property must be configured as `false` in order to be able to use the Azure properties. It is `true` by default. |
```

2021-03-19 16:27 UTC, viliam-durina commented on README.md
> +| k8sServiceDnsTimeout           | Integer | Custom time for how long the DNS Lookup is checked |
```suggestion
| k8sServiceDnsTimeout           | Integer | Custom time for how long the DNS lookup is valid |
```

2021-03-19 16:27 UTC, viliam-durina commented on README.md
> +| k8sNamespace                   | String  | Kubernetes Namespace where Hazelcast is running |
```suggestion
| k8sNamespace                   | String  | Kubernetes namespace where Hazelcast is running |
```

2021-03-19 16:27 UTC, viliam-durina commented on README.md
> +#### Hazelcast cloud configuration
```suggestion
#### Hazelcast Cloud Configuration
```

2021-03-19 16:27 UTC, viliam-durina commented on README.md
> +For connecting to the Hazelcast cloud you only need to specify `discoveryToken` property and use `cluster-name` as a host in
```suggestion
For connecting to the Hazelcast cloud you only need to specify `discoveryToken` property and use the `cluster-name` as a host in 
```

2021-03-22 09:04 UTC, SeriyBg commented on README.md
> +**schema**: (Required) Hazelcast schema name.
Did we decide to remove it? As @devozerov mentioned it seems that our `schema` parameter is ok here, as it sets the namespace

2021-03-22 09:10 UTC, SeriyBg commented on README.md
> +| trustCertCollectionFile        | String  | Path to truststore file |
It is because both params are aliases

2021-03-22 09:51 UTC, viliam-durina approved these changes
I created two follow-up issues: #62, #60

2021-03-22 09:55 UTC, viliam-durina commented on README.md
> +**schema**: (Required) Hazelcast schema name.
I created a followup issue #60, let's discuss it there.

2021-03-22 09:56 UTC, viliam-durina commented on README.md
> +| clusterName                    | String  | Hazelcast cluster name |
Created a followup issue #62, let's don't resolve it here.

2021-03-22 09:57 UTC, viliam-durina commented on README.md
> +| trustCertCollectionFile        | String  | Path to truststore file |
Then it would be better to mention it here...

2021-03-22 10:51 UTC, merged