Schema
hazelcast/hazelcast-jdbc pull request #61
Opened 2021-03-22 09:12 UTC by SeriyBg

Fix #58

2021-03-22 13:15 UTC, viliam-durina requested changes

2021-03-22 13:15 UTC, viliam-durina commented on src/test/java/com/hazelcast/jdbc/JdbcConnectionIntegrationTest.java
> +    @Disabled("SQL module for now ignores the schema parameter from the API")
This comment isn't correct. You requested `WrongSchema`, but it's not ignored. The query doesn't contain any schema, so it tries to resolve the `person` table from `WrongSchema`. It's not there, so it proceeds with the default schemas, that is `public` and then `partitioned`. So it's correct that this test doesn't fail. 

You should do a test with Jet. Create a map `m` and also a mapping `m`. Both should have different columns or contentes. Without `setSchema`, the mapping should be used. If you set `partitioned` schema, the imap should be used directly, you can assert the returned columns.

2021-03-22 18:03 UTC, devozerov commented
LGTM except for Villiam's comment.

2021-03-22 18:03 UTC, devozerov approved these changes

2021-03-23 09:38 UTC, SeriyBg commented
The PR is blocked by: https://github.com/hazelcast/hazelcast/issues/18428

2021-03-26 11:50 UTC, Fly-Style approved these changes

2021-09-17 13:29 UTC, viliam-durina approved these changes

2021-09-17 14:10 UTC, hakanmemisoglu approved these changes

2021-09-17 14:14 UTC, merged